services:
    api: &api
        build:
            context: .
            dockerfile: ./docker/production/django/Dockerfile
        volumes:
            - ./staticfiles:/app/staticfiles
            - app_logs:/app/logs
        ports:
            - "8001:8000"
        env_file:
            - ./.envs/.env.production
        depends_on:
            - postgres
            - redis
            - rabbitmq
        command: /start.sh
        networks:
            - fundflowhub_prod_nw
    
    postgres:
        build:
            context: .
            dockerfile: ./docker/production/postgres/Dockerfile
        ports:
            - "5432:5432"
        volumes:
            - fundflowhub_prod_db:/var/lib/postgresql/data
            - ./backups:/backups
        env_file:
            - ./.envs/.env.production
        networks:
            - fundflowhub_prod_nw
    
    redis:
        image: redis:7.0-alpine3.19
        command: redis-server --appendonly yes
        networks:
            - fundflowhub_prod_nw
    
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
            - rabbitmq_log:/var/log/rabbitmq
        networks:
            - fundflowhub_prod_nw
    
    celeryworker:
        <<: *api
        command: /start-celeryworker.sh
        
    flower:
        <<: *api
        ports:
            - "5555:5555"
        volumes:
            - flower_db:/app/flower_db
        command: /start-flower.sh
    
    celerybeat:
        build:
            context: .
            dockerfile: ./docker/production/django/Dockerfile
        command: /start-celerybeat.sh
        volumes:
            - ./staticfiles:/app/staticfiles
            - app_logs:/app/logs
        env_file:
            - ./.envs/.env.production
        depends_on:
            - redis
            - postgres
            - rabbitmq
        networks:
            - fundflowhub_prod_nw

    # nginx handled by host Nginx (shared with other VPS sites)

networks:
    fundflowhub_prod_nw:
        external: true

volumes:
    fundflowhub_prod_db:
    app_logs:
    rabbitmq_data:
    rabbitmq_log:
    flower_db:
    
    
    
    
    